version: '3.3'
services:
    web:
        image: robertfreeman/coin_web
        deploy:
            mode: replicated
            replicas: 2
        ports:
            - 8082
        networks:
            - backend
            - ucp-hrm

    hasher:
        image: robertfreeman/robhasher
        deploy:
            mode: replicated
            replicas: 2
        networks:
            - backend

    redis:
        image: robertfreeman/redis-cont
        networks:
            - backend

networks:
    backend:
