version: '3.3'
services:
    web:
        image: robertfreeman/coin_web
        deploy:
            mode: replicated
            replicas: 2
            labels:
                com.docker.ucp.mesh.http.8082: "external_route=http://robcoin.ucp.robert.dtcntr.net,internal_port=8082"
        image: robertfreeman/coin_web
        ports:
            - 8082
        networks:
            - backend
            - ucp-hrm

    hasher:
        image: robertfreeman/robhasher
        deploy:
            mode: replicated
            replicas: 2
        networks:
            - backend

    redis:
        image: robertfreeman/redis-cont
        networks:
            - backend

networks:
    backend:
    ucp-hrm:
        external: true
