version: '3.3'
services:
    web:
        image: robertfreeman/robcoin_gui
        deploy:
            mode: replicated
            replicas: 2
        ports:
            - 80
        networks:
            - backend

    api:
        image: robertfreeman/tempapi
        ports:
            - 8082:8082
        networks:
            - backend

    hasher:
        image: robertfreeman/robhasher
        deploy:
            mode: replicated
            replicas: 2
        networks:
            - backend

    redis:
        image: robertfreeman/redis-cont
        networks:
            - backend

networks:
    backend:
